import type { FlowSceneDefinition, FlowSceneStep } from "../core/flow-scene/types";
import type { Representation } from "../core/trace-engine/types";

function step(definition: FlowSceneStep): FlowSceneStep {
  return definition;
}

function text(
  representation: Representation,
  copy: {
    abstract: string;
    practical?: string;
    memory?: string;
  },
) {
  if (representation === "practical") return copy.practical ?? copy.abstract;
  if (representation === "memory") return copy.memory ?? copy.abstract;
  return copy.abstract;
}

export function createDijkstraFlowScene(representation: Representation): FlowSceneDefinition {
  return {
    id: `dijkstra-weighted-graph-${representation}`,
    sceneKind: "graph",
    title: "Dijkstra: menor custo em grafo ponderado",
    description: "A cena mostra distâncias provisórias, relaxamentos, fila de prioridade e a reconstrução do menor caminho.",
    legend: [
      { semantic: "request", label: "Fronteira" },
      { semantic: "processing", label: "Nó atual" },
      { semantic: "success", label: "Relaxamento aceito" },
      { semantic: "error", label: "Relaxamento rejeitado" },
      { semantic: "result", label: "Menor caminho" },
    ],
    graph: {
      sourceId: "A",
      targetId: "E",
      priorityQueue: [{ nodeId: "A", distance: 0 }],
      nodes: [
        {
          id: "A",
          label: "A",
          description: "origem do algoritmo",
          position: {
            desktop: { x: 0.14, y: 0.44 },
            mobile: { x: 0.5, y: 0.18 },
          },
          distance: 0,
          predecessorId: null,
        },
        {
          id: "B",
          label: "B",
          description: "vizinho intermediário",
          position: {
            desktop: { x: 0.34, y: 0.2 },
            mobile: { x: 0.26, y: 0.4 },
          },
          distance: "∞",
          predecessorId: null,
        },
        {
          id: "C",
          label: "C",
          description: "vizinho barato a partir de A",
          position: {
            desktop: { x: 0.36, y: 0.66 },
            mobile: { x: 0.74, y: 0.4 },
          },
          distance: "∞",
          predecessorId: null,
        },
        {
          id: "D",
          label: "D",
          description: "nó penúltimo antes do alvo",
          position: {
            desktop: { x: 0.63, y: 0.26 },
            mobile: { x: 0.28, y: 0.66 },
          },
          distance: "∞",
          predecessorId: null,
        },
        {
          id: "E",
          label: "E",
          description: "alvo do menor caminho",
          position: {
            desktop: { x: 0.78, y: 0.58 },
            mobile: { x: 0.72, y: 0.66 },
          },
          distance: "∞",
          predecessorId: null,
        },
      ],
      edges: [
        { id: "ab", from: "A", to: "B", weight: 4 },
        { id: "ac", from: "A", to: "C", weight: 2 },
        { id: "cb", from: "C", to: "B", weight: 1 },
        { id: "bd", from: "B", to: "D", weight: 5 },
        { id: "cd", from: "C", to: "D", weight: 8 },
        { id: "ce", from: "C", to: "E", weight: 10 },
        { id: "be", from: "B", to: "E", weight: 12 },
        { id: "de", from: "D", to: "E", weight: 2 },
      ],
    },
    steps: [
      step({
        id: "dijkstra-graph-start",
        title: "Inicializar origem e distâncias",
        caption: text(representation, {
          abstract: "Todos os nós começam com ∞, exceto a origem A, que começa com 0.",
          practical: "A rota começa em A com custo 0; todos os outros pontos ainda são desconhecidos.",
        }),
        focusNodeId: "A",
        concept: {
          title: "Dijkstra começa com uma única certeza",
          bubble: "No início, só sabemos que a distância da origem até ela mesma é zero.",
          summary: "O algoritmo parte de uma fonte única. Todas as outras distâncias são provisórias e começam como infinito até que algum caminho as descubra.",
          longform: [
            "Essa convenção evita suposições prematuras. Em vez de preencher o grafo com palpites, Dijkstra constrói conhecimento aos poucos, sempre a partir do menor custo conhecido.",
            "A fila de prioridade também começa mínima: só a origem entra nela. O restante do grafo ainda não foi descoberto.",
          ],
          details: [
            "A = 0 porque estamos partindo de A.",
            "B, C, D e E começam como ∞.",
            "A fila de prioridade recebe apenas (A, 0).",
          ],
          glossary: [
            { term: "Distância provisória", definition: "Melhor custo conhecido até agora para alcançar um nó." },
            { term: "∞", definition: "O algoritmo ainda não conhece caminho algum até esse nó." },
          ],
          payloadTitle: "Estado inicial",
          payloadLines: [
            "A = 0",
            "B = ∞",
            "C = ∞",
            "D = ∞",
            "E = ∞",
            "pq = [(A, 0)]",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "set-graph-source", nodeId: "A" },
          { type: "set-graph-target", nodeId: "E" },
          { type: "set-graph-node-state", nodeId: "A", state: "frontier" },
          { type: "update-graph-priority-queue", items: [{ nodeId: "A", distance: 0 }] },
        ],
      }),
      step({
        id: "dijkstra-select-a",
        title: "Extrair o menor nó da fila",
        caption: "A fila remove A porque 0 é a menor distância conhecida no momento.",
        focusNodeId: "A",
        concept: {
          title: "O nó atual sempre é o menor custo disponível",
          bubble: "Dijkstra não escolhe um nó arbitrário: ele sempre processa o menor custo conhecido na fila.",
          summary: "Esse é o ponto que distingue o algoritmo. A fila de prioridade garante que o próximo nó processado seja o mais promissor disponível.",
          details: [
            "A é removido da fila.",
            "A passa para o estado current.",
            "Enquanto A estiver current, suas arestas vizinhas serão inspecionadas.",
          ],
          payloadTitle: "Fila após o pop",
          payloadLines: [
            "extractMin() = A",
            "pq = []",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "dequeue-graph-min", nodeId: "A" },
          { type: "set-current-graph-node", nodeId: "A" },
        ],
      }),
      step({
        id: "dijkstra-inspect-ab",
        title: "Inspecionar A → B",
        caption: "A aresta A → B produz distância candidata 4, melhor que ∞.",
        focusNodeId: "B",
        concept: {
          title: "Inspecionar uma aresta é calcular um caminho candidato",
          bubble: "Cada vizinho recebe uma proposta: distância atual do nó corrente + peso da aresta.",
          summary: "Relaxar não é atualizar por atualizar. Antes de qualquer mudança, o algoritmo calcula quanto custaria chegar ao vizinho passando pelo nó atual.",
          details: [
            "Distância atual de A = 0.",
            "Peso de A → B = 4.",
            "Candidato para B = 0 + 4 = 4.",
            "Como 4 < ∞, B será atualizado.",
          ],
          payloadTitle: "Cálculo",
          payloadLines: [
            "dist(A) = 0",
            "w(A→B) = 4",
            "candidato(B) = 4",
            "conhecido(B) = ∞",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "set-current-graph-node", nodeId: "A" },
          { type: "inspect-graph-edge", edgeId: "ab" },
          { type: "calculate-graph-candidate", from: "A", to: "B", currentDistance: 0, edgeWeight: 4, candidateDistance: 4, knownDistance: "∞" },
          { type: "relax-graph-edge", edgeId: "ab", nodeId: "B", previousDistance: "∞", newDistance: 4, predecessorId: "A" },
          { type: "update-graph-priority-queue", items: [{ nodeId: "B", distance: 4 }] },
        ],
      }),
      step({
        id: "dijkstra-inspect-ac",
        title: "Inspecionar A → C",
        caption: "A aresta A → C produz distância 2 e reorganiza a fila de prioridade.",
        focusNodeId: "C",
        concept: {
          title: "A fila precisa reagir à nova prioridade",
          bubble: "Quando C recebe 2, ele passa à frente de B na fila porque 2 < 4.",
          summary: "Não basta descobrir um vizinho. O algoritmo também precisa reordenar a fronteira para refletir o menor custo conhecido.",
          details: [
            "Distância atual de A = 0.",
            "Peso de A → C = 2.",
            "C recebe distância 2 e predecessor A.",
            "A fila vira [(C,2), (B,4)].",
          ],
          payloadTitle: "Fila atualizada",
          payloadLines: [
            "dist(C) = 2",
            "pred(C) = A",
            "pq = [(C,2), (B,4)]",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "set-current-graph-node", nodeId: "A" },
          { type: "set-graph-node-state", nodeId: "B", state: "frontier" },
          { type: "inspect-graph-edge", edgeId: "ac" },
          { type: "calculate-graph-candidate", from: "A", to: "C", currentDistance: 0, edgeWeight: 2, candidateDistance: 2, knownDistance: "∞" },
          { type: "relax-graph-edge", edgeId: "ac", nodeId: "C", previousDistance: "∞", newDistance: 2, predecessorId: "A" },
          { type: "update-graph-priority-queue", items: [{ nodeId: "C", distance: 2 }, { nodeId: "B", distance: 4 }] },
        ],
      }),
      step({
        id: "dijkstra-visit-a-select-c",
        title: "Fechar A e escolher C",
        caption: "Depois de avaliar os vizinhos de A, o algoritmo fecha A e segue para C.",
        focusNodeId: "C",
        concept: {
          title: "Visited significa custo finalizado",
          bubble: "Quando um nó sai como mínimo e seus vizinhos são processados, ele é fechado como visited.",
          summary: "Para Dijkstra com pesos não negativos, o nó fechado já não precisa ser revisitado com custo menor. Agora a atenção se move para C, o menor da fila.",
          details: [
            "A muda para visited.",
            "C é retirado da fila como novo current.",
            "B continua na fronteira com custo 4.",
          ],
          payloadTitle: "Novo estado da fila",
          payloadLines: [
            "visited = {A}",
            "current = C",
            "pq = [(B,4)]",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "mark-graph-visited", nodeId: "A" },
          { type: "set-graph-node-state", nodeId: "B", state: "frontier" },
          { type: "dequeue-graph-min", nodeId: "C" },
          { type: "set-current-graph-node", nodeId: "C" },
          { type: "update-graph-priority-queue", items: [{ nodeId: "B", distance: 4 }] },
        ],
      }),
      step({
        id: "dijkstra-relax-cb",
        title: "Relaxar C → B",
        caption: "Passar por C melhora B de 4 para 3.",
        focusNodeId: "B",
        concept: {
          title: "Relaxar é substituir um caminho por outro mais barato",
          bubble: "B já tinha uma distância conhecida, mas C oferece um caminho melhor.",
          summary: "Esse é o coração do algoritmo. Uma relaxação aceita não descobre apenas um nó novo; ela também pode melhorar uma estimativa anterior.",
          details: [
            "Distância atual de C = 2.",
            "Peso de C → B = 1.",
            "Candidato para B = 3.",
            "Como 3 < 4, B muda de 4 para 3 e passa a apontar para C.",
          ],
          payloadTitle: "Decrease-key conceitual",
          payloadLines: [
            "dist(B): 4 → 3",
            "pred(B): A → C",
            "pq = [(B,3)]",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "mark-graph-visited", nodeId: "A" },
          { type: "set-current-graph-node", nodeId: "C" },
          { type: "inspect-graph-edge", edgeId: "cb" },
          { type: "calculate-graph-candidate", from: "C", to: "B", currentDistance: 2, edgeWeight: 1, candidateDistance: 3, knownDistance: 4 },
          { type: "relax-graph-edge", edgeId: "cb", nodeId: "B", previousDistance: 4, newDistance: 3, predecessorId: "C" },
          { type: "update-graph-priority-queue", items: [{ nodeId: "B", distance: 3 }] },
        ],
      }),
      step({
        id: "dijkstra-relax-cd",
        title: "Relaxar C → D",
        caption: "D é descoberto com custo 10 a partir de C.",
        focusNodeId: "D",
        concept: {
          title: "Descobrir um nó novo também é relaxamento",
          bubble: "Quando o destino conhecido era ∞, qualquer caminho finito já é uma melhora aceita.",
          summary: "D ainda não existia na fronteira. A aresta C → D cria a primeira estimativa concreta para ele.",
          details: [
            "Distância atual de C = 2.",
            "Peso de C → D = 8.",
            "D recebe 10 e predecessor C.",
            "A fila passa a conter B e D.",
          ],
          payloadTitle: "Fronteira expandida",
          payloadLines: [
            "dist(D) = 10",
            "pred(D) = C",
            "pq = [(B,3), (D,10)]",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "mark-graph-visited", nodeId: "A" },
          { type: "set-current-graph-node", nodeId: "C" },
          { type: "set-graph-node-state", nodeId: "B", state: "frontier" },
          { type: "inspect-graph-edge", edgeId: "cd" },
          { type: "calculate-graph-candidate", from: "C", to: "D", currentDistance: 2, edgeWeight: 8, candidateDistance: 10, knownDistance: "∞" },
          { type: "relax-graph-edge", edgeId: "cd", nodeId: "D", previousDistance: "∞", newDistance: 10, predecessorId: "C" },
          { type: "update-graph-priority-queue", items: [{ nodeId: "B", distance: 3 }, { nodeId: "D", distance: 10 }] },
        ],
      }),
      step({
        id: "dijkstra-relax-ce",
        title: "Relaxar C → E",
        caption: "E entra na fronteira com custo 12, mas ainda pode melhorar depois.",
        focusNodeId: "E",
        concept: {
          title: "O primeiro caminho até o alvo ainda não é necessariamente o melhor",
          bubble: "Dijkstra não para ao primeiro contato com E se ainda há nós mais baratos na fila.",
          summary: "E já aparece com custo 12, mas esse valor continua provisório enquanto existirem candidatos mais baratos para explorar.",
          details: [
            "Distância atual de C = 2.",
            "Peso de C → E = 10.",
            "E recebe 12 e predecessor C.",
            "B ainda é o menor da fila com custo 3.",
          ],
          pitfalls: [
            "Encontrar o alvo cedo não significa, por si só, que o caminho final está fechado.",
          ],
          payloadTitle: "Fila após descobrir E",
          payloadLines: [
            "dist(E) = 12",
            "pred(E) = C",
            "pq = [(B,3), (D,10), (E,12)]",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "mark-graph-visited", nodeId: "A" },
          { type: "set-current-graph-node", nodeId: "C" },
          { type: "set-graph-node-state", nodeId: "B", state: "frontier" },
          { type: "set-graph-node-state", nodeId: "D", state: "frontier" },
          { type: "inspect-graph-edge", edgeId: "ce" },
          { type: "calculate-graph-candidate", from: "C", to: "E", currentDistance: 2, edgeWeight: 10, candidateDistance: 12, knownDistance: "∞" },
          { type: "relax-graph-edge", edgeId: "ce", nodeId: "E", previousDistance: "∞", newDistance: 12, predecessorId: "C" },
          { type: "update-graph-priority-queue", items: [{ nodeId: "B", distance: 3 }, { nodeId: "D", distance: 10 }, { nodeId: "E", distance: 12 }] },
        ],
      }),
      step({
        id: "dijkstra-visit-c-select-b",
        title: "Fechar C e escolher B",
        caption: "C é finalizado; B assume como menor custo restante na fila.",
        focusNodeId: "B",
        concept: {
          title: "A fronteira continua mudando de acordo com o menor custo",
          bubble: "Mesmo com D e E descobertos, B vem primeiro porque 3 é o menor valor da fila.",
          summary: "Dijkstra não segue pela geometria do desenho nem pela ordem em que os nós apareceram. Ele segue exclusivamente pelo menor custo conhecido.",
          details: [
            "A e C agora estão visited.",
            "B passa a ser current com custo 3.",
            "D e E permanecem frontier.",
          ],
          payloadTitle: "Fila restante",
          payloadLines: [
            "visited = {A, C}",
            "current = B",
            "pq = [(D,10), (E,12)]",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "mark-graph-visited", nodeId: "A" },
          { type: "mark-graph-visited", nodeId: "C" },
          { type: "set-graph-node-state", nodeId: "D", state: "frontier" },
          { type: "set-graph-node-state", nodeId: "E", state: "frontier" },
          { type: "dequeue-graph-min", nodeId: "B" },
          { type: "set-current-graph-node", nodeId: "B" },
          { type: "update-graph-priority-queue", items: [{ nodeId: "D", distance: 10 }, { nodeId: "E", distance: 12 }] },
        ],
      }),
      step({
        id: "dijkstra-relax-bd",
        title: "Relaxar B → D",
        caption: "Passar por B melhora D de 10 para 8.",
        focusNodeId: "D",
        concept: {
          title: "Uma melhora tardia ainda pode vencer a estimativa anterior",
          bubble: "D já tinha 10 via C, mas B oferece caminho mais barato: 3 + 5 = 8.",
          summary: "Esse passo mostra por que Dijkstra mantém distâncias provisórias. O primeiro valor conhecido de um nó não é tratado como definitivo até que ele seja o menor retirado da fila.",
          details: [
            "Distância atual de B = 3.",
            "Peso de B → D = 5.",
            "Candidato para D = 8.",
            "Como 8 < 10, D melhora e troca de predecessor.",
          ],
          payloadTitle: "Atualização em D",
          payloadLines: [
            "dist(D): 10 → 8",
            "pred(D): C → B",
            "pq = [(D,8), (E,12)]",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "mark-graph-visited", nodeId: "A" },
          { type: "mark-graph-visited", nodeId: "C" },
          { type: "set-current-graph-node", nodeId: "B" },
          { type: "set-graph-node-state", nodeId: "D", state: "frontier" },
          { type: "set-graph-node-state", nodeId: "E", state: "frontier" },
          { type: "inspect-graph-edge", edgeId: "bd" },
          { type: "calculate-graph-candidate", from: "B", to: "D", currentDistance: 3, edgeWeight: 5, candidateDistance: 8, knownDistance: 10 },
          { type: "relax-graph-edge", edgeId: "bd", nodeId: "D", previousDistance: 10, newDistance: 8, predecessorId: "B" },
          { type: "update-graph-priority-queue", items: [{ nodeId: "D", distance: 8 }, { nodeId: "E", distance: 12 }] },
        ],
      }),
      step({
        id: "dijkstra-reject-be",
        title: "Rejeitar B → E",
        caption: "Nem toda aresta inspecionada melhora a solução: 15 é pior que 12.",
        focusNodeId: "E",
        concept: {
          title: "Relaxação rejeitada também ensina o algoritmo",
          bubble: "O cálculo continua sendo feito, mas o estado não muda quando o caminho candidato é pior.",
          summary: "Esse caso é pedagogicamente importante porque mostra que Dijkstra não atualiza por impulso. Ele compara a proposta nova com a distância conhecida e só aceita melhora real.",
          details: [
            "Distância atual de B = 3.",
            "Peso de B → E = 12.",
            "Candidato para E = 15.",
            "Como 15 ≥ 12, E permanece com 12 e predecessor C.",
          ],
          payloadTitle: "Comparação rejeitada",
          payloadLines: [
            "candidato(E) = 15",
            "conhecido(E) = 12",
            "resultado = rejeitar",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "mark-graph-visited", nodeId: "A" },
          { type: "mark-graph-visited", nodeId: "C" },
          { type: "set-current-graph-node", nodeId: "B" },
          { type: "set-graph-node-state", nodeId: "D", state: "frontier" },
          { type: "set-graph-node-state", nodeId: "E", state: "frontier" },
          { type: "inspect-graph-edge", edgeId: "be" },
          { type: "calculate-graph-candidate", from: "B", to: "E", currentDistance: 3, edgeWeight: 12, candidateDistance: 15, knownDistance: 12 },
          { type: "reject-graph-relaxation", edgeId: "be", nodeId: "E" },
          { type: "update-graph-priority-queue", items: [{ nodeId: "D", distance: 8 }, { nodeId: "E", distance: 12 }] },
        ],
      }),
      step({
        id: "dijkstra-visit-b-select-d",
        title: "Fechar B e escolher D",
        caption: "Com B finalizado, o próximo menor custo é D com 8.",
        focusNodeId: "D",
        concept: {
          title: "A fila continua sendo a autoridade do próximo passo",
          bubble: "Depois de fechar B, a menor prioridade restante pertence a D.",
          summary: "Os nós visitados deixam de disputar a fila. O algoritmo segue apenas com a melhor opção aberta entre as distâncias provisórias restantes.",
          details: [
            "Visited = {A, C, B}.",
            "D passa a ser current com custo 8.",
            "E continua na fronteira com custo 12.",
          ],
          payloadTitle: "Fila após B",
          payloadLines: [
            "current = D",
            "pq = [(E,12)]",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "mark-graph-visited", nodeId: "A" },
          { type: "mark-graph-visited", nodeId: "C" },
          { type: "mark-graph-visited", nodeId: "B" },
          { type: "set-graph-node-state", nodeId: "E", state: "frontier" },
          { type: "dequeue-graph-min", nodeId: "D" },
          { type: "set-current-graph-node", nodeId: "D" },
          { type: "update-graph-priority-queue", items: [{ nodeId: "E", distance: 12 }] },
        ],
      }),
      step({
        id: "dijkstra-relax-de",
        title: "Relaxar D → E",
        caption: "D melhora E de 12 para 10 e aproxima o menor caminho final.",
        focusNodeId: "E",
        concept: {
          title: "A melhor rota até o alvo aparece por refinamento",
          bubble: "E já era conhecido, mas D abre um caminho ainda mais barato: 8 + 2 = 10.",
          summary: "O alvo melhora de novo. Isso mostra visualmente a propagação do custo mínimo conforme o algoritmo fecha nós baratos e expande suas arestas.",
          details: [
            "Distância atual de D = 8.",
            "Peso de D → E = 2.",
            "Candidato para E = 10.",
            "Como 10 < 12, E troca de predecessor e passa a apontar para D.",
          ],
          payloadTitle: "Ajuste final em E",
          payloadLines: [
            "dist(E): 12 → 10",
            "pred(E): C → D",
            "pq = [(E,10)]",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "mark-graph-visited", nodeId: "A" },
          { type: "mark-graph-visited", nodeId: "C" },
          { type: "mark-graph-visited", nodeId: "B" },
          { type: "set-current-graph-node", nodeId: "D" },
          { type: "set-graph-node-state", nodeId: "E", state: "frontier" },
          { type: "inspect-graph-edge", edgeId: "de" },
          { type: "calculate-graph-candidate", from: "D", to: "E", currentDistance: 8, edgeWeight: 2, candidateDistance: 10, knownDistance: 12 },
          { type: "relax-graph-edge", edgeId: "de", nodeId: "E", previousDistance: 12, newDistance: 10, predecessorId: "D" },
          { type: "update-graph-priority-queue", items: [{ nodeId: "E", distance: 10 }] },
        ],
      }),
      step({
        id: "dijkstra-reconstruct",
        title: "Reconstruir o menor caminho",
        caption: "Percorrendo os predecessores de E, o caminho final fica A → C → B → D → E.",
        focusNodeId: "E",
        concept: {
          title: "O caminho mínimo final nasce dos predecessores",
          bubble: "A distância final não basta sozinha; o algoritmo também preserva quem levou a cada melhoria.",
          summary: "Para reconstruir o caminho, partimos do alvo E e seguimos seus predecessores até a origem. O resultado final é A → C → B → D → E com custo total 10.",
          longform: [
            "Esse fechamento é a prova visual de que as relaxações anteriores não eram apenas números soltos. Cada melhora deixou um predecessor, e a cadeia desses predecessores vira o caminho mínimo.",
            "No estado pausado, o usuário consegue ver claramente quais nós pertencem ao caminho final e quais arestas realmente compõem a solução.",
          ],
          details: [
            "pred(E) = D",
            "pred(D) = B",
            "pred(B) = C",
            "pred(C) = A",
            "Custo total = 10",
          ],
          glossary: [
            { term: "Predecessor", definition: "Nó imediatamente anterior no melhor caminho conhecido até aqui." },
            { term: "Reconstrução", definition: "Etapa de percorrer predecessores do alvo de volta até a origem." },
          ],
          payloadTitle: "Caminho final",
          payloadLines: [
            "A → C → B → D → E",
            "2 + 1 + 5 + 2 = 10",
          ],
        },
        actions: [
          { type: "reset-graph-state" },
          { type: "mark-graph-visited", nodeId: "A" },
          { type: "mark-graph-visited", nodeId: "C" },
          { type: "mark-graph-visited", nodeId: "B" },
          { type: "mark-graph-visited", nodeId: "D" },
          { type: "update-graph-priority-queue", items: [] },
          { type: "reconstruct-graph-path", nodeIds: ["A", "C", "B", "D", "E"], edgeIds: ["ac", "cb", "bd", "de"], totalCost: 10 },
        ],
      }),
    ],
  };
}
